# author: Fabian Wilms

language: node_js
node_js: 
  - "node"
before_script:
  - npm install -g bower polymer-cli
  - bower install
script:
  - polymer build

  
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/es6-bundled
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master